# Generated by Django 5.2.14 on 2026-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('section', models.CharField(choices=[('home', 'Home / Hero'), ('projects', 'Projects'), ('case_study', 'Case Study'), ('future', 'Future Projects'), ('contact', 'Contact'), ('default', 'Default / Global')], default='default', max_length=20)),
                ('default_volume', models.FloatField(default=0.4, help_text='0.0 to 1.0')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
