# Generated by Django 5.2.14 on 2026-08-30 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutureProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('concept', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('concept', 'Concept'), ('research', 'Research'), ('development', 'Development'), ('testing', 'Testing'), ('live', 'Live')], default='concept', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(blank=True, help_text='Leave blank to hide progress bar', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/future/')),
                ('technologies_planned', models.CharField(blank=True, help_text='Comma-separated', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=300)),
                ('full_description', models.TextField()),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('architecture', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('learning', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/')),
                ('hover_gif', models.FileField(blank=True, null=True, upload_to='projects/gifs/')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/videos/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#9333ea', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Project Technologies',
            },
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='projects.projecttechnology'),
        ),
    ]
