# Generated by Django 5.2.14 on 2026-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Role',
                'verbose_name_plural': 'Hero Roles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Nagasrinivas Govvala', max_length=200)),
                ('title', models.CharField(default='Fresher Software Developer', max_length=200)),
                ('location', models.CharField(default='Hyderabad, Telangana, India', max_length=200)),
                ('email', models.EmailField(default='nagasrinivas@email.com', max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('about_short', models.TextField(default='A fresher software developer who builds real applications.')),
                ('about_long', models.TextField(default='')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('available_for_work', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Personal Profile',
                'verbose_name_plural': 'Personal Profile',
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Nagasrinivas Govvala | Fresher Software Developer', max_length=200)),
                ('meta_description', models.TextField(default='Nagasrinivas Govvala — Fresher Software Developer from Hyderabad. Python, Django, AI/ML, Full-Stack web development.', max_length=300)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('google_site_verification', models.CharField(blank=True, max_length=200)),
                ('canonical_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Nagasrinivas Govvala', max_length=200)),
                ('tagline', models.CharField(default='Building practical software with Python, Django, AI and modern web technologies.', max_length=500)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo_text', models.CharField(default='NG.', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('analytics_code', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
