# Generated by Django 5.2.14 on 2026-09-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='resume_external_url',
            field=models.URLField(blank=True, help_text='Optional external link (e.g. Google Drive, S3, Dropbox). If set, this URL is used for download.'),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='resume_file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='resume_filename',
            field=models.CharField(blank=True, default='Nagasrinivas_Govvala_Resume.pdf', max_length=255),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload a resume file (PDF recommended).', null=True, upload_to='resume/'),
        ),
    ]
