# Generated by Django 5.2.14 on 2026-09-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personalprofile_resume_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='about_long',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='about_short',
            field=models.TextField(blank=True, default='A fresher software developer who builds real applications.'),
        ),
    ]
