# Generated by Django 5.2.14 on 2026-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('model', models.CharField(default='mistralai/mistral-7b-instruct', max_length=100)),
                ('max_tokens', models.PositiveIntegerField(default=500)),
                ('temperature', models.FloatField(default=0.3)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=20)),
                ('welcome_message', models.TextField(default="Hi. I'm Srinivas AI. Ask me about Nagasrinivas's projects, skills, education, technologies or development work.")),
                ('system_prompt_extra', models.TextField(blank=True, help_text='Additional instructions appended to the system prompt')),
            ],
            options={
                'verbose_name': 'Chatbot Settings',
                'verbose_name_plural': 'Chatbot Settings',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
