# Generated by Django 5.2.14 on 2026-09-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotsettings',
            name='max_tokens',
            field=models.PositiveIntegerField(default=1024),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='model',
            field=models.CharField(default='google/gemini-2.5-flash', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='temperature',
            field=models.FloatField(default=0.4),
        ),
    ]
