# Generated by Django 5.2.14 on 2026-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=300)),
                ('year', models.PositiveIntegerField()),
                ('grade', models.CharField(help_text='e.g. CGPA: 7.17 or Percentage: 70%', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
    ]
