# Generated by Django 5.2.14 on 2026-08-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(help_text='e.g. 2022-2025 or 2019-2022', max_length=50),
        ),
    ]
