# Generated by Django 5.2.14 on 2026-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('web', 'Web'), ('data_ml', 'Data / ML'), ('database', 'Database'), ('cloud', 'Cloud'), ('tools', 'Tools'), ('ai_tools', 'AI Development Tools')], max_length=50)),
                ('proficiency', models.CharField(choices=[('primary', 'Primary'), ('working', 'Working Knowledge'), ('familiar', 'Familiar')], default='working', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='SVG icon name or emoji', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('web', 'Web'), ('data_ml', 'Data / ML'), ('database', 'Database'), ('cloud', 'Cloud'), ('tools', 'Tools'), ('ai_tools', 'AI Development Tools')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='What has Nagasrinivas used it for?')),
                ('related_project', models.CharField(blank=True, help_text='e.g. ResumeAI, Toxic Comment Classification', max_length=200)),
                ('color', models.CharField(default='#9333ea', help_text='Hex color for the node', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'order'],
            },
        ),
    ]
