# Generated by Django 5.2.14 on 2026-08-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', '-start_date']},
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_type',
            field=models.CharField(choices=[('part_time', 'Part-Time'), ('virtual_internship', 'Virtual Internship / Training'), ('internship', 'Internship / Training'), ('freelance', 'Freelance'), ('project', 'Project')], default='part_time', max_length=30),
        ),
    ]
